#! /bin/bash


ENDDOC='\\end{document}'
BIBTEX="\\\nocite{*} \\\bibliographystyle{alpha} \\\bibliography{../../Documentation/biblio} ${ENDDOC}"
ENDSTY='\\endinput'

# removing the symlink
rm doc.docdir

# adding bibtex reference
sed "s=${ENDDOC}=${BIBTEX}=g" _build/doc.docdir/doc.tex > temp
mv temp _build/doc.docdir/doc.tex

# adding macros in ocamldoc.sty
sed "s=${ENDSTY}==g" _build/doc.docdir/ocamldoc.sty > temp
echo '\endinput' | cat temp Documentation/macro-command.tex - > _build/doc.docdir/ocamldoc.sty
rm temp



# ending message
BLU='\e[;34m' # blue
NC='\033[0m' # no color
BOLD=$(tput bold) # bold printing
NF=$(tput sgr0) # no format
printf "${BLU}Documentation --> ${BOLD}_build/doc.docdir/index.html${BLU} or ${BOLD}_build/doc.docdir/doc.tex${BLU} ${NC}\n"
